version: '3'

services:
  service1:
    image: mikys997/fivelab:latest
    ports:
      - "6666:80"
    deploy:
      replicas: 1
    networks:
      - my_network

networks:
  my_network:
    external:true

